CREATE DATABASE "object-store-1";
GRANT ALL PRIVILEGES ON DATABASE "object-store-1" TO postgres;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE DATABASE "object-store-2";
GRANT ALL PRIVILEGES ON DATABASE "object-store-2" TO postgres;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
