version: '3.5'

services:

    postgres-cee:
        image: postgres:13-alpine
        container_name: postgres-cee
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password1
        networks:
            - p8e-network
        ports:
            - "5432:5432"
        volumes:
            - postgres-cee:/var/lib/postgresql/data
            - ./db-init:/docker-entrypoint-initdb.d/
        healthcheck:
            test: [ CMD-SHELL, pg_isready -U postgres ]
            interval: 5s
            timeout: 10s
            retries: 5
        command: postgres

    object-store-1:
        image: ghcr.io/provenance-io/object-store:0.7.0
        container_name: object-store-1
        depends_on:
            - postgres-cee
        env_file:
            - object-store-1.env
        networks:
            - p8e-network
        ports:
            - "5001:8080"
        volumes:
            - ./object-store-1:/mnt/data

    object-store-2:
        image: ghcr.io/provenance-io/object-store:0.7.0
        container_name: object-store-2
        depends_on:
            - postgres-cee
        env_file:
            - object-store-2.env
        networks:
            - p8e-network
        ports:
            - "5002:8080"
        volumes:
            - ./object-store-2:/mnt/data

    provenance:
        image: provenanceio/provenance:v1.16.0
        container_name: provenance
        command: bash -c "cp -rn /home/provenance_seed/* /provenance && /usr/bin/provenanced -t --home /provenance start"
        networks:
            - p8e-network
        ports:
            - "1317:1317"
            - "9090:9090"
            - "26657:26657"
        environment:
            - ID=dev
            - PIO_HOME=/provenance
        volumes:
            - ./prov-init:/home/provenance_seed:ro
            - provenance:/provenance

    vault:
        image: hashicorp/vault:1.14.4
        container_name: vault-cee
        networks:
            - p8e-network
        ports:
            - "8200:8200"
        restart: always
        environment:
            - VAULT_DEV_ROOT_TOKEN_ID=root
            - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
        cap_add:
            - IPC_LOCK
        entrypoint: vault server -dev

    object-store-gateway:
        image: figuretechnologies/object-store-gateway:3.2.0
        container_name: p8e-cee-local-object-store-gateway
        networks:
            - p8e-network
        depends_on:
            - object-store-1
            - object-store-2
            - provenance
        environment:
            - EVENT_STREAM_WEBSOCKET_URI=ws://host.docker.internal:26657
            - EVENT_STREAM_EPOCH_HEIGHT=1
            - EVENT_STREAM_ENABLED=true
            - EVENT_STREAM_BLOCK_HEIGHT_TRACKING_UUID=f83b43fe-b536-11ec-b558-0bfb50e52d23
            - OBJECTSTORE_URI=grpc://host.docker.internal:5001
            - OBJECTSTORE_PRIVATE_KEYS=0A201AD27E627DD0A6A5816D293C41DF801D3E7BA868EEC0F433FDA581D71E38016E
            - OBJECTSTORE_MASTER_KEY=0A201AD27E627DD0A6A5816D293C41DF801D3E7BA868EEC0F433FDA581D71E38016E
            - PROVENANCE_MAIN_NET=false
            - PROVENANCE_CHAIN_ID=chain-local
            - PROVENANCE_CHANNEL_URI=http://provenance:9090
            - DB_TYPE=memory
            - DB_NAME=object-store-gateway
            - DB_USERNAME=user
            - DB_PASSWORD=pass
            - DB_HOST=memory
            - DB_PORT=
            - DB_SCHEMA=object-store-gateway
            - DB_CONNECTION_POOL_SIZE=1
            - DB_BASELINE_ON_MIGRATE=false
            - DB_REPAIR_FLYWAY_CHECKSUMS=false
            - SERVER_PORT=8091
        ports:
            - "16549:8080" # All GRPC requests should be made on port 16549 to ensure other local apps can still stand up on port 8080
            - "8091:8091"
volumes:
    postgres-cee:
    provenance:
    object-store-1:
    object-store-2:

networks:
  p8e-network:
    ipam:
      driver: default
      config:
        - subnet: 172.19.10.0/24
